#include "PluginProcessor.h"
#include "PluginEditor.h"
GlassAudioProcessor::GlassAudioProcessor():AudioProcessor(BusesProperties().withInput("Input",juce::AudioChannelSet::stereo(),true).withOutput("Output",juce::AudioChannelSet::stereo(),true)),apvts(*this,nullptr,"PARAMETERS",layout()){}
juce::AudioProcessorValueTreeState::ParameterLayout GlassAudioProcessor::layout(){juce::AudioProcessorValueTreeState::ParameterLayout l;l.add(std::make_unique<juce::AudioParameterFloat>("drive","Drive",juce::NormalisableRange<float>(0,30,.01f),12));l.add(std::make_unique<juce::AudioParameterFloat>("character","2nd Harmonic",juce::NormalisableRange<float>(0,1,.001f),.35f));l.add(std::make_unique<juce::AudioParameterFloat>("bias","Bias",juce::NormalisableRange<float>(-1,1,.001f),0));l.add(std::make_unique<juce::AudioParameterFloat>("mix","Mix",juce::NormalisableRange<float>(0,1,.001f),1));l.add(std::make_unique<juce::AudioParameterFloat>("output","Output",juce::NormalisableRange<float>(-24,12,.01f),-6));l.add(std::make_unique<juce::AudioParameterBool>("original","Original Circuit",true));return l;}
void GlassAudioProcessor::prepareToPlay(double sr,int){for(auto& t:tube)t.prepare(sr);}
bool GlassAudioProcessor::isBusesLayoutSupported(const BusesLayout& l)const{return l.getMainInputChannelSet()==l.getMainOutputChannelSet()&&(l.getMainOutputChannelSet()==juce::AudioChannelSet::mono()||l.getMainOutputChannelSet()==juce::AudioChannelSet::stereo());}
void GlassAudioProcessor::processBlock(juce::AudioBuffer<float>& b,juce::MidiBuffer&){juce::ScopedNoDenormals n;float d=apvts.getRawParameterValue("drive")->load(),c=apvts.getRawParameterValue("character")->load(),bi=apvts.getRawParameterValue("bias")->load(),m=apvts.getRawParameterValue("mix")->load(),outDb=apvts.getRawParameterValue("output")->load(),o=juce::Decibels::decibelsToGain(outDb);bool orig=apvts.getRawParameterValue("original")->load()>.5f;for(int ch=0;ch<b.getNumChannels();++ch){auto*p=b.getWritePointer(ch);for(int i=0;i<b.getNumSamples();++i){float dry=p[i],wet=tube[juce::jmin(ch,1)].process(dry,d,c,bi,orig);p[i]=std::tanh((dry*(1-m)+wet*m)*o);}}}
void GlassAudioProcessor::getStateInformation(juce::MemoryBlock& d){auto x=apvts.copyState().createXml();copyXmlToBinary(*x,d);}void GlassAudioProcessor::setStateInformation(const void*d,int s){auto x=getXmlFromBinary(d,s);if(x)apvts.replaceState(juce::ValueTree::fromXml(*x));}
juce::AudioProcessorEditor* GlassAudioProcessor::createEditor(){return new GlassAudioProcessorEditor(*this);}juce::AudioProcessor* JUCE_CALLTYPE createPluginFilter(){return new GlassAudioProcessor();}
